/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import RoundedField.RoundJPanel;
import ScrollBar.MyScrollBarUI;
import java.awt.Color;
import java.awt.Container;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import javax.swing.ScrollPaneLayout;
import javax.swing.SwingUtilities;
import m.banking.DateBankRut;
import m.banking.Kurs;
import m.banking.Login.Login;
import m.banking.Member;

/**
 *
 * @author LINGGO
 */
public class AdminDashboard extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboard
     */
    AdminHomepage ah;
    Login l;
    DateBankRut d1;
    ArrayList<Kurs> listKurs = new ArrayList<>();
    public AdminDashboard() {
        initComponents();
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        String filename = "date.ser";
        try {
            FileInputStream file = new FileInputStream(filename);
            ObjectInputStream in = new ObjectInputStream(file);

            d1 = (DateBankRut) in.readObject();

            in.close();
            file.close();
            System.out.println(d1.getD1().getDate() + " - " + d1.getD1().getMonth() + " - " + d1.getD1().getYear());
        }
        catch(IOException ex) {
            System.out.println("IOException is caught");
        }
        catch(ClassNotFoundException ex) {
            System.out.println("ClassNotFoundException is caught");
        }
        try {
            FileInputStream file = new FileInputStream("Kurs.ser");
            ObjectInputStream in = new ObjectInputStream(file);

            listKurs = (ArrayList<Kurs>) in.readObject();

            in.close();
            file.close();
            System.out.println("Dollar : " + listKurs.get(0).getKursBeli());
            System.out.println("Euro : " + listKurs.get(1).getKursBeli());
        }
        catch(IOException ex) {
            System.out.println("IOException is caught");
        }
        catch(ClassNotFoundException ex) {
            System.out.println("ClassNotFoundException is caught");
        }
        String bulan = "";
        if (d1.getD1().getMonth() == 1){
            bulan = "Januari";
        }
        else if (d1.getD1().getMonth() == 2){
            bulan = "Februari";
        }
        else if (d1.getD1().getMonth() == 3){
            bulan = "Maret";
        }
        else if (d1.getD1().getMonth() == 4){
            bulan = "April";
        }
        else if (d1.getD1().getMonth() == 5){
            bulan = "Mei";
        }
        else if (d1.getD1().getMonth() == 6){
            bulan = "Juni";
        }
        else if (d1.getD1().getMonth() == 7){
            bulan = "Juli";
        }
        else if (d1.getD1().getMonth() == 8){
            bulan = "Agustus";
        }
        else if (d1.getD1().getMonth() == 9){
            bulan = "September";
        }
        else if (d1.getD1().getMonth() == 10){
            bulan = "Oktober";
        }
        else if (d1.getD1().getMonth() == 11){
            bulan = "November";
        }
        else if (d1.getD1().getMonth() == 12){
            bulan = "Desember";
        }
        date.setText(d1.getD1().getDate() + " " + bulan + " " + d1.getD1().getYear());
        Color green = new Color(0,102,51);
        Color red = new Color(153,0,0);
        lblKursBeliUSD.setText(listKurs.get(0).getKursBeli()+"");
        if(listKurs.get(0).getPersen() >= 0) {
            lblPersenUSD.setText("+" + listKurs.get(0).getPersen() + "%");
            lblPersenUSD.setForeground(green);
        } 
        else {
            lblPersenUSD.setText(listKurs.get(0).getPersen() + "%");
            lblPersenUSD.setForeground(red);
        }
        lblKursBeliEuro.setText(listKurs.get(1).getKursBeli()+"");
        if(listKurs.get(1).getPersen() >= 0) {
            lblPersenEuro.setText("+" + listKurs.get(1).getPersen()+"%");
            lblPersenEuro.setForeground(green);
        } 
        else {
            lblPersenEuro.setText(listKurs.get(1).getPersen()+"%");
            lblPersenEuro.setForeground(red);
        }
    }
    
    public void getAdmin(AdminHomepage ah){
        this.ah = ah;
    }
    
    public void passData(Login l){
        this.l = l;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        Hello = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Logo = new RoundJPanel(35);
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        isi1 = new RoundJPanel(30);
        jPanel4 = new RoundJPanel(35);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        isi2 = new RoundJPanel(30);
        jPanel5 = new RoundJPanel(35);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        isi4 = new RoundJPanel(30);
        jPanel1 = new RoundJPanel(35);
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new RoundJPanel(25);
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new RoundJPanel(25);
        name = new javax.swing.JLabel();
        jPanel11 = new RoundJPanel(25);
        point = new javax.swing.JLabel();
        jPanel2 = new RoundJPanel(35);
        jPanel9 = new RoundJPanel(25);
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel7 = new RoundJPanel(35);
        jPanel8 = new RoundJPanel(25);
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new RoundJPanel(25);
        jLabel17 = new javax.swing.JLabel();
        lblKursBeliUSD = new javax.swing.JLabel();
        lblPersenUSD = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblKursBeliEuro = new javax.swing.JLabel();
        lblPersenEuro = new javax.swing.JLabel();

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.getVerticalScrollBar().setUI(new MyScrollBarUI());
        MouseAdapter ma1 = new MouseAdapter() {

            private Point origin;

            @Override
            public void mousePressed(MouseEvent e) {
                origin = new Point(e.getPoint());
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                if (origin != null) {
                    JViewport viewPort = (JViewport) SwingUtilities.getAncestorOfClass(JViewport.class, content);
                    if (viewPort != null) {
                        int deltaX = origin.x - e.getX();
                        int deltaY = origin.y - e.getY();

                        Rectangle view = viewPort.getViewRect();
                        view.x += deltaX;
                        view.y += deltaY;

                        content.scrollRectToVisible(view);
                    }
                }
            }

        };

        content.addMouseListener(ma1);
        content.addMouseMotionListener(ma1);

        content.setBackground(new java.awt.Color(250, 243, 243));

        Hello.setBackground(new java.awt.Color(51, 51, 51));
        Hello.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Hello.setForeground(new java.awt.Color(0, 0, 0));
        Hello.setText("Hello, Admin,");

        Welcome.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(0, 0, 0));
        Welcome.setText("Welcome back!");

        Logo.setBackground(new java.awt.Color(73, 79, 88));
        Logo.setOpaque(false);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/logo_bank.2.png"))); // NOI18N

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(250, 243, 243));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        //jScrollPane1.setLayout(new ScrollPaneLayout() {
            //      @Override
            //      public void layoutContainer(Container parent) {
                //        JScrollPane scrollPane = (JScrollPane) parent;
                //
                //        Rectangle availR = scrollPane.getBounds();
                //        availR.x = availR.y = 0;
                //
                //        Insets parentInsets = parent.getInsets();
                //        availR.x = parentInsets.left;
                //        availR.y = parentInsets.top;
                //        availR.width -= parentInsets.left + parentInsets.right;
                //        availR.height -= parentInsets.top + parentInsets.bottom;
                //
                //        Rectangle vsbR = new Rectangle();
                //        vsbR.width = 12;
                //        vsbR.height = availR.height;
                //        vsbR.x = availR.x + availR.width - vsbR.width;
                //        vsbR.y = availR.y;
                //
                //        if (viewport != null) {
                    //          viewport.setBounds(availR);
                    //        }
                //        if (vsb != null) {
                    //          vsb.setVisible(false);
                    //          vsb.setBounds(vsbR);
                    //        }
                //      }
            //    });
    jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollBarUI());

    MouseAdapter ma = new MouseAdapter() {

        private Point origin;

        @Override
        public void mousePressed(MouseEvent e) {
            origin = new Point(e.getPoint());
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseDragged(MouseEvent e) {
            if (origin != null) {
                JViewport viewPort = (JViewport) SwingUtilities.getAncestorOfClass(JViewport.class, jPanel6);
                if (viewPort != null) {
                    int deltaX = origin.x - e.getX();
                    int deltaY = origin.y - e.getY();

                    Rectangle view = viewPort.getViewRect();
                    view.x += deltaX;
                    view.y += deltaY;

                    jPanel6.scrollRectToVisible(view);
                }
            }
        }

    };

    jPanel6.addMouseListener(ma);
    jPanel6.addMouseMotionListener(ma);

    jPanel6.setBackground(new java.awt.Color(250, 243, 243));
    jPanel6.setPreferredSize(new java.awt.Dimension(600, 241));

    isi1.setBackground(new java.awt.Color(254, 174, 72));
    isi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    isi1.setOpaque(false);
    isi1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            isi1MouseClicked(evt);
        }
    });

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setOpaque(false);

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/calendar.png"))); // NOI18N

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
    );

    jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Date");

    jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Change");

    jLabel6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Date, Month, Year");

    javax.swing.GroupLayout isi1Layout = new javax.swing.GroupLayout(isi1);
    isi1.setLayout(isi1Layout);
    isi1Layout.setHorizontalGroup(
        isi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(isi1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(isi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6)
                .addComponent(jLabel5)
                .addComponent(jLabel4))
            .addContainerGap(29, Short.MAX_VALUE))
    );
    isi1Layout.setVerticalGroup(
        isi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(isi1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel6)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    isi2.setBackground(new java.awt.Color(73, 79, 88));
    isi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    isi2.setOpaque(false);
    isi2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            isi2MouseClicked(evt);
        }
    });

    jPanel5.setBackground(new java.awt.Color(255, 255, 255));
    jPanel5.setOpaque(false);

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/log.png"))); // NOI18N

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel7)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Watch");

    jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setText("Log");

    jLabel10.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setText("Log All Member");

    javax.swing.GroupLayout isi2Layout = new javax.swing.GroupLayout(isi2);
    isi2.setLayout(isi2Layout);
    isi2Layout.setHorizontalGroup(
        isi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(isi2Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(isi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10)
                .addComponent(jLabel9)
                .addComponent(jLabel8)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(53, Short.MAX_VALUE))
    );
    isi2Layout.setVerticalGroup(
        isi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(isi2Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel10)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    isi4.setBackground(new java.awt.Color(84, 190, 229));
    isi4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    isi4.setOpaque(false);
    isi4.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            isi4MouseClicked(evt);
        }
    });

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setOpaque(false);

    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/exit.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel12.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setText("Log out");

    javax.swing.GroupLayout isi4Layout = new javax.swing.GroupLayout(isi4);
    isi4.setLayout(isi4Layout);
    isi4Layout.setHorizontalGroup(
        isi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(isi4Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(isi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(67, Short.MAX_VALUE))
    );
    isi4Layout.setVerticalGroup(
        isi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(isi4Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel12)
            .addContainerGap(112, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(isi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
            .addComponent(isi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(isi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE)))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(isi4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()))
    );

    jScrollPane1.setViewportView(jPanel6);

    jPanel3.setBackground(new java.awt.Color(0, 255, 204));
    jPanel3.setOpaque(false);

    jLabel11.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel11.setText("Highest point");

    jPanel10.setBackground(new java.awt.Color(51, 255, 51));
    jPanel10.setOpaque(false);

    name.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    name.setText("jLabel15");
    ArrayList<Member> Account = new ArrayList<>();
    try {
        FileInputStream file = new FileInputStream("Account.ser");
        ObjectInputStream in = new ObjectInputStream(file);

        Account = (ArrayList<Member>) in.readObject();

        in.close();
        file.close();
    }
    catch(IOException ex) {
        System.out.println("IOException is caught");
    }
    catch(ClassNotFoundException ex) {
        System.out.println("ClassNotFoundException is caught");
    }
    String temp1 = "abcde";
    int max = 0;
    for (int i = 0; i < Account.size(); i++){
        if (Account.get(i).getPoint() >= max){
            max = Account.get(i).getPoint();
            temp1 = Account.get(i).getNama();
        }
    }
    System.out.println(temp1);
    name.setText(temp1);

    jPanel11.setBackground(new java.awt.Color(102, 102, 255));
    jPanel11.setOpaque(false);

    point.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    point.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    point.setText("jLabel16");
    point.setText(String.valueOf(max));

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel11Layout.setVerticalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(point)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
            .addContainerGap(110, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(110, 110, 110))
    );
    jPanel10Layout.setVerticalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(13, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(19, 19, 19))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel11)
            .addGap(30, 30, 30)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(84, 190, 229));
    jPanel2.setOpaque(false);
    jPanel2.setPreferredSize(new java.awt.Dimension(224, 116));

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));
    jPanel9.setOpaque(false);

    jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Current Date");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
    );

    date.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    date.setForeground(new java.awt.Color(0, 0, 0));
    date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    date.setText("tgl");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(41, 41, 41)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(39, Short.MAX_VALUE))
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(date)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel7.setBackground(new java.awt.Color(254, 174, 72));
    jPanel7.setOpaque(false);
    jPanel7.setPreferredSize(new java.awt.Dimension(224, 116));

    jPanel8.setBackground(new java.awt.Color(255, 255, 255));
    jPanel8.setOpaque(false);

    jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Kurs");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
    );

    jPanel12.setBackground(new java.awt.Color(250, 223, 116));
    jPanel12.setOpaque(false);

    jLabel17.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(0, 0, 0));
    jLabel17.setText("USD");

    lblKursBeliUSD.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    lblKursBeliUSD.setForeground(new java.awt.Color(0, 0, 0));
    lblKursBeliUSD.setText("14000");

    lblPersenUSD.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    lblPersenUSD.setForeground(new java.awt.Color(0, 0, 0));
    lblPersenUSD.setText("+3.82%");

    jLabel18.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    jLabel18.setForeground(new java.awt.Color(0, 0, 0));
    jLabel18.setText("EURO");

    lblKursBeliEuro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    lblKursBeliEuro.setForeground(new java.awt.Color(0, 0, 0));
    lblKursBeliEuro.setText("14000");

    lblPersenEuro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    lblPersenEuro.setForeground(new java.awt.Color(0, 0, 0));
    lblPersenEuro.setText("+3.82%");

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jLabel17)
                    .addGap(31, 31, 31)
                    .addComponent(lblKursBeliUSD))
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKursBeliEuro)))
            .addGap(27, 27, 27)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(lblPersenUSD)
                .addComponent(lblPersenEuro))
            .addContainerGap(16, Short.MAX_VALUE))
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17)
                .addComponent(lblKursBeliUSD)
                .addComponent(lblPersenUSD))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(lblKursBeliEuro)
                .addComponent(lblPersenEuro))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addContainerGap(21, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13))
    );

    javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
    content.setLayout(contentLayout);
    contentLayout.setHorizontalGroup(
        contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        .addGroup(contentLayout.createSequentialGroup()
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(contentLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Welcome)
                        .addComponent(Hello)))
                .addGroup(contentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGap(0, 37, Short.MAX_VALUE))
    );
    contentLayout.setVerticalGroup(
        contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(contentLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(Hello)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Welcome)))
            .addGap(32, 32, 32)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jScrollPane2.setViewportView(content);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void isi4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isi4MouseClicked
        this.setVisible(false);
        Login l = new Login();
        l.setVisible(true);
        ah.setVisible(false);
    }//GEN-LAST:event_isi4MouseClicked

    private void isi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isi1MouseClicked
        // TODO add your handling code here:
        ah.getContent().removeAll();
        AdminChangeDate acd = new AdminChangeDate();
        acd.passDashboad(this);
        acd.setVisible(true);
        acd.setBounds(0,0, 512, 825);
        ah.getContent().add(acd);
        ah.getContent().revalidate();
        ah.getContent().repaint();
    }//GEN-LAST:event_isi1MouseClicked

    private void isi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isi2MouseClicked
        // TODO add your handling code here:
        ah.getContent().removeAll();
        AdminLog AL = new AdminLog();
        AL.passDashboad(this);
        AL.setVisible(true);
        AL.setBounds(0,0, 512, 825);
        ah.getContent().add(AL);
        ah.getContent().revalidate();
        ah.getContent().repaint();
    }//GEN-LAST:event_isi2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hello;
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel content;
    private javax.swing.JLabel date;
    private javax.swing.JPanel isi1;
    private javax.swing.JPanel isi2;
    private javax.swing.JPanel isi4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKursBeliEuro;
    private javax.swing.JLabel lblKursBeliUSD;
    private javax.swing.JLabel lblPersenEuro;
    private javax.swing.JLabel lblPersenUSD;
    private javax.swing.JLabel name;
    private javax.swing.JLabel point;
    // End of variables declaration//GEN-END:variables
    
    public void setDate(String txt){
        date.setText(txt);
    }
}
