/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import RoundedField.RoundJPanel;
import ScrollBar.MyScrollBarUI;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneLayout;
import javax.swing.SwingUtilities;
import m.banking.Gold;
import m.banking.Member;
import m.banking.Platinum;
import m.banking.Silver;

/**
 *
 * @author LINGGO
 */
public class AdminBannedMember extends javax.swing.JPanel {

    /**
     * Creates new form AdminNewMember
     */
    ArrayList<Member> requestMember;
    int idx = -1;
    public AdminBannedMember() {
        initComponents();
        showAllRequestMember();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        listnewMember = new javax.swing.JPanel();
        deleteMember = new RoundJPanel(25);
        jLabel4 = new javax.swing.JLabel();
        unbanned = new RoundJPanel(25);
        unbannnedLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 243, 243));

        scroll.setBackground(new java.awt.Color(250, 243, 243));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setLayout(new ScrollPaneLayout() {
            @Override
            public void layoutContainer(Container parent) {
                JScrollPane scrollPane = (JScrollPane) parent;

                Rectangle availR = scrollPane.getBounds();
                availR.x = availR.y = 0;

                Insets parentInsets = parent.getInsets();
                availR.x = parentInsets.left;
                availR.y = parentInsets.top;
                availR.width -= parentInsets.left + parentInsets.right;
                availR.height -= parentInsets.top + parentInsets.bottom;

                Rectangle vsbR = new Rectangle();
                vsbR.width = 12;
                vsbR.height = availR.height;
                vsbR.x = availR.x + availR.width - vsbR.width;
                vsbR.y = availR.y;

                if (viewport != null) {
                    viewport.setBounds(availR);
                }
                if (vsb != null) {
                    vsb.setVisible(true);
                    vsb.setBounds(vsbR);
                }
            }
        });
        scroll.getVerticalScrollBar().setUI(new MyScrollBarUI());
        MouseAdapter ma = new MouseAdapter() {

            private Point origin;

            @Override
            public void mousePressed(MouseEvent e) {
                origin = new Point(e.getPoint());
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                if (origin != null) {
                    JViewport viewPort = (JViewport) SwingUtilities.getAncestorOfClass(JViewport.class, listnewMember);
                    if (viewPort != null) {
                        int deltaX = origin.x - e.getX();
                        int deltaY = origin.y - e.getY();

                        Rectangle view = viewPort.getViewRect();
                        view.x += deltaX;
                        view.y += deltaY;

                        listnewMember.scrollRectToVisible(view);
                    }
                }
            }

        };

        listnewMember.addMouseListener(ma);
        listnewMember.addMouseMotionListener(ma);

        listnewMember.setBackground(new java.awt.Color(250, 243, 243));

        javax.swing.GroupLayout listnewMemberLayout = new javax.swing.GroupLayout(listnewMember);
        listnewMember.setLayout(listnewMemberLayout);
        listnewMemberLayout.setHorizontalGroup(
            listnewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        listnewMemberLayout.setVerticalGroup(
            listnewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        scroll.setViewportView(listnewMember);

        deleteMember.setBackground(new java.awt.Color(255, 102, 102));
        deleteMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteMember.setOpaque(false);
        deleteMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMemberMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/trash.png"))); // NOI18N
        jLabel4.setText("Delete");

        javax.swing.GroupLayout deleteMemberLayout = new javax.swing.GroupLayout(deleteMember);
        deleteMember.setLayout(deleteMemberLayout);
        deleteMemberLayout.setHorizontalGroup(
            deleteMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        deleteMemberLayout.setVerticalGroup(
            deleteMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        unbanned.setBackground(new java.awt.Color(51, 255, 51));
        unbanned.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unbanned.setOpaque(false);
        unbanned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unbannedMouseClicked(evt);
            }
        });

        unbannnedLbl.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        unbannnedLbl.setForeground(new java.awt.Color(0, 0, 0));
        unbannnedLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unbannnedLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/unban.png"))); // NOI18N
        unbannnedLbl.setText("Unbanned");

        javax.swing.GroupLayout unbannedLayout = new javax.swing.GroupLayout(unbanned);
        unbanned.setLayout(unbannedLayout);
        unbannedLayout.setHorizontalGroup(
            unbannedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unbannedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unbannnedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        unbannedLayout.setVerticalGroup(
            unbannedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unbannedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unbannnedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
            .addGroup(layout.createSequentialGroup()
                .addComponent(unbanned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(unbanned, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMemberMouseClicked
        // TODO add your handling code here:
        if (idx != -1){
            ArrayList<Member> banned = new ArrayList<>();
            try {
                FileInputStream file = new FileInputStream("BannedAccount.ser");
                ObjectInputStream in = new ObjectInputStream(file);

                banned = (ArrayList<Member>) in.readObject();

                in.close();
                file.close();
            }
            catch(IOException ex) {
                System.out.println("IOException is caught");
            }
            catch(ClassNotFoundException ex) {
                System.out.println("ClassNotFoundException is caught");
            }
            banned.remove(idx);
            try {
                FileOutputStream file = new FileOutputStream("BannedAccount.ser");
                ObjectOutputStream out = new ObjectOutputStream(file);

                out.writeObject(banned);

                out.close();
                file.close();

                System.out.println("Object has been serialized");

            }
            catch(IOException ex) {
                System.out.println("IOException is caught");
            }
            JOptionPane.showMessageDialog(this, "Success Delete");
        }
        else {
            JOptionPane.showMessageDialog(this, "Pick a new member pls");
        }
        idx = -1;
        showAllRequestMember();
    }//GEN-LAST:event_deleteMemberMouseClicked

    private void unbannedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unbannedMouseClicked
        // TODO add your handling code here:
        if (idx != -1){
            ArrayList<Member> Account = new ArrayList<>();
            try {
                FileInputStream file = new FileInputStream("Account.ser");
                ObjectInputStream in = new ObjectInputStream(file);

                Account = (ArrayList<Member>) in.readObject();

                in.close();
                file.close();
            }
            catch(IOException ex) {
                System.out.println("IOException is caught1");
            }
            catch(ClassNotFoundException ex) {
                System.out.println("ClassNotFoundException is caught");
            }
            
            ArrayList<Member> banned = new ArrayList<>();
            try {
                FileInputStream file = new FileInputStream("BannedAccount.ser");
                ObjectInputStream in = new ObjectInputStream(file);

                banned = (ArrayList<Member>) in.readObject();

                in.close();
                file.close();
            }
            catch(IOException ex) {
                System.out.println("IOException is caught");
            }
            catch(ClassNotFoundException ex) {
                System.out.println("ClassNotFoundException is caught");
            }
            
            Account.add(banned.get(idx));
            banned.remove(idx);
            
            try {
                FileOutputStream file = new FileOutputStream("Account.ser");
                ObjectOutputStream out = new ObjectOutputStream(file);

                out.writeObject(Account);

                out.close();
                file.close();

                System.out.println("Object has been serialized");

            }
            catch(IOException ex) {
                System.out.println("IOException is caught2");
                System.out.println(ex);
            }
            
            try {
                FileOutputStream file = new FileOutputStream("BannedAccount.ser");
                ObjectOutputStream out = new ObjectOutputStream(file);

                out.writeObject(banned);

                out.close();
                file.close();

                System.out.println("Object has been serialized");

            }
            catch(IOException ex) {
                System.out.println("IOException is caught");
            }
            
            JOptionPane.showMessageDialog(this, "Berhasil Blokir Member " + Account.get(Account.size()-1).getNama());
        }
        else {
            JOptionPane.showMessageDialog(this, "Pick a new member pls");
        }
        idx = -1;
        showAllRequestMember();
    }//GEN-LAST:event_unbannedMouseClicked

    public boolean isNumeric(String str){
        for (char c : str.toCharArray())
        {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    
    public void showAllRequestMember(){
        ArrayList<Member> banned = new ArrayList<>();
        ArrayList<AdminCardListMember> ACLM = new ArrayList<>();
        try {
            FileInputStream file = new FileInputStream("BannedAccount.ser");
            ObjectInputStream in = new ObjectInputStream(file);

            banned = (ArrayList<Member>) in.readObject();

            in.close();
            file.close();
        }
        catch(IOException ex) {
            System.out.println("IOException is caught");
        }
        catch(ClassNotFoundException ex) {
            System.out.println("ClassNotFoundException is caught");
        }
        listnewMember.removeAll();
        if ((205+10)*banned.size() >= 460) {
            listnewMember.setPreferredSize(new Dimension(470, (205+10)*banned.size()));
        }
        else {
            listnewMember.setPreferredSize(new Dimension(488, 460));
        }
        for (int i = 0; i < banned.size(); i++) {
            System.out.println(i);
            ACLM.add(new AdminCardListMember());
            ACLM.get(i).setName("ALNM"+i);
            ACLM.get(i).setFullName("Full Name     : " + banned.get(i).getNama().toUpperCase());
            String tempnorek = banned.get(i).getNoRekening().substring(0,4) + "-" + banned.get(i).getNoRekening().substring(4,8) + "-" + banned.get(i).getNoRekening().substring(8,12) + "-" + banned.get(i).getNoRekening().substring(12,16);
            ACLM.get(i).setNoRek("Card Number   : " + tempnorek);
            String tempSaldo = Double.toString(banned.get(i).getRupiah());
            ACLM.get(i).setSaldo("Balance       : " + priceWithoutDecimal(banned.get(i).getRupiah()));
            String jenis = "";
            if (banned.get(i) instanceof Silver){
                jenis = "Silver";
                ACLM.get(i).setNewColorKartu(229, 228, 226);
            }
            else if (banned.get(i) instanceof Gold){
                jenis = "Gold";
                ACLM.get(i).setNewColorKartu(255,215,0);
            }
            else if (banned.get(i) instanceof Platinum){
                jenis = "Platinum";
                ACLM.get(i).setNewColorKartu(128,128,128);
            }
            ACLM.get(i).setJenisKartu(jenis);
            ACLM.get(i).setBounds(0, (205+10)*i, 470,205);
            ACLM.get(i).setVisible(true);
            ACLM.get(i).addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e){
                    System.out.println("klik");
                    System.out.println(e.getSource());
                    System.out.println(e.getY());
                    System.out.println(e.getComponent().getName());
                    System.out.println(ACLM.indexOf(e.getComponent()));
                    idx = ACLM.indexOf(e.getComponent());
                    resetBGPanel(ACLM);
                    ACLM.get(idx).setNewColorBG(84,190,229);
                }
            });
            listnewMember.add(ACLM.get(i));
        }
        listnewMember.revalidate();
        listnewMember.repaint();
    }

    public void resetBGPanel(ArrayList<AdminCardListMember> ACLM){
        ArrayList<Member> Account = new ArrayList<>();
        try {
            FileInputStream file = new FileInputStream("Account.ser");
            ObjectInputStream in = new ObjectInputStream(file);

            Account = (ArrayList<Member>) in.readObject();

            in.close();
            file.close();
        }
        catch(IOException ex) {
            System.out.println("IOException is caught");
        }
        catch(ClassNotFoundException ex) {
            System.out.println("ClassNotFoundException is caught");
        }
        for (int j = 0; j < Account.size(); j++) {
            ACLM.get(j).setNewColorBG(255,255,255);
        }
    }
    
    public String priceWithoutDecimal (Double price) {
        DecimalFormat formatter = new DecimalFormat("###,###,###.##");
        return formatter.format(price);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deleteMember;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel listnewMember;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel unbanned;
    private javax.swing.JLabel unbannnedLbl;
    // End of variables declaration//GEN-END:variables
}
