/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import RoundedField.RoundJPanel;
import java.awt.Color;

/**
 *
 * @author LINGGO
 */
public class AdminCardListMember extends javax.swing.JPanel {

    /**
     * Creates new form AdminListNewMember
     */
    public AdminCardListMember() {
        initComponents();
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundJPanel(50);
        bg = new RoundJPanel(50);
        fullName = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        noRek = new javax.swing.JLabel();
        kartu = new RoundJPanel(20);
        jenisKartu = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.setOpaque(false);

        fullName.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        fullName.setForeground(new java.awt.Color(0, 0, 0));
        fullName.setText("Full Name     : ADMIN");

        saldo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        saldo.setForeground(new java.awt.Color(0, 0, 0));
        saldo.setText("Balance       : 0");

        noRek.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        noRek.setForeground(new java.awt.Color(0, 0, 0));
        noRek.setText("Card Number   : 1234-5678");

        kartu.setBackground(new java.awt.Color(204, 204, 204));
        kartu.setOpaque(false);

        jenisKartu.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jenisKartu.setForeground(new java.awt.Color(0, 0, 0));
        jenisKartu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jenisKartu.setText("Platinum");

        javax.swing.GroupLayout kartuLayout = new javax.swing.GroupLayout(kartu);
        kartu.setLayout(kartuLayout);
        kartuLayout.setHorizontalGroup(
            kartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisKartu, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        kartuLayout.setVerticalGroup(
            kartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisKartu)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noRek)
                    .addComponent(saldo)
                    .addComponent(fullName))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fullName)
                .addGap(18, 18, 18)
                .addComponent(noRek)
                .addGap(18, 18, 18)
                .addComponent(saldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(kartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel fullName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKartu;
    private javax.swing.JPanel kartu;
    private javax.swing.JLabel noRek;
    private javax.swing.JLabel saldo;
    // End of variables declaration//GEN-END:variables
    
    public void setNewColorBG(int w1, int w2, int w3){
        this.bg.setBackground(new Color(w1,w2,w3));
    }
    
    public void setNewColorKartu(int w1, int w2, int w3){
        this.kartu.setBackground(new Color(w1, w2, w3));
    }
    
    public void setFullName(String fullname){
        this.fullName.setText(fullname);
    }

    public void setNoRek(String noRek){
        this.noRek.setText(noRek);
    }
    
    public void setSaldo(String saldo){
        this.saldo.setText(saldo);
    }
    
    public void setJenisKartu(String jenis){
        this.jenisKartu.setText(jenis);
    }
}
