/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Image.ImagePanel;
import RoundedField.RoundJPanel;
import m.banking.Gold;
import m.banking.Silver;

/**
 *
 * @author acxel
 */
public class UserProfile extends javax.swing.JPanel {

    /**
     * Creates new form UserProfile
     */
    
    UserHomepage uh;
    
    public UserProfile(UserHomepage uh) {
        this.uh = uh;
        initComponents();
        if(uh.active instanceof Silver) {
            lblJenisKartu.setText("SILVER");
        } else if (uh.active instanceof Gold) {
            lblJenisKartu.setText("GOLD");
        } else {
            lblJenisKartu.setText("PLATINUM");
        }
        String tempIsiKartu = String.valueOf(uh.active.getNoRekening()).substring(0,4) + " " + String.valueOf(uh.active.getNoRekening()).substring(4,8);
        lblNomorKartu.setText(tempIsiKartu);
    }
    
    public void passData(UserHomepage uh) {
        this.uh = uh;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblJenisKartu = new javax.swing.JLabel();
        btnGantiPin = new RoundJPanel(35);
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAturLimit = new RoundJPanel(35);
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTagihan = new RoundJPanel(35);
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new RoundJPanel(35);
        jLabel7 = new javax.swing.JLabel();
        String temp = "";
        if(uh.active instanceof Silver) {
            temp =  "src/m/banking/Asset/silver.png";
        } else if (uh.active instanceof Gold) {
            temp =  "src/m/banking/Asset/gold.png";
        } else {
            temp =  "src/m/banking/Asset/platinum.png";
        }
        gambarKartu = new ImagePanel(temp);
        lblNomorKartu = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(250, 243, 243));

        lblJenisKartu.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        lblJenisKartu.setForeground(new java.awt.Color(0, 0, 0));
        lblJenisKartu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJenisKartu.setText("JENIS");

        btnGantiPin.setBackground(new java.awt.Color(103, 91, 232));
        btnGantiPin.setForeground(new java.awt.Color(0, 51, 255));
        btnGantiPin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGantiPin.setOpaque(false);
        btnGantiPin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGantiPinMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 53, 61));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GANTI PIN");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/password1.png"))); // NOI18N

        javax.swing.GroupLayout btnGantiPinLayout = new javax.swing.GroupLayout(btnGantiPin);
        btnGantiPin.setLayout(btnGantiPinLayout);
        btnGantiPinLayout.setHorizontalGroup(
            btnGantiPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGantiPinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnGantiPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnGantiPinLayout.setVerticalGroup(
            btnGantiPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGantiPinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnAturLimit.setBackground(new java.awt.Color(87, 202, 247));
        btnAturLimit.setForeground(new java.awt.Color(0, 51, 255));
        btnAturLimit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAturLimit.setOpaque(false);
        btnAturLimit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAturLimitMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 53, 61));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ATUR LIMIT");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/speedometer.png"))); // NOI18N

        javax.swing.GroupLayout btnAturLimitLayout = new javax.swing.GroupLayout(btnAturLimit);
        btnAturLimit.setLayout(btnAturLimitLayout);
        btnAturLimitLayout.setHorizontalGroup(
            btnAturLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAturLimitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAturLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnAturLimitLayout.setVerticalGroup(
            btnAturLimitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAturLimitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );

        btnTagihan.setBackground(new java.awt.Color(249, 117, 218));
        btnTagihan.setForeground(new java.awt.Color(0, 51, 255));
        btnTagihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTagihan.setOpaque(false);
        btnTagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTagihanMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 53, 61));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TAGIHAN");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/Note.png"))); // NOI18N

        javax.swing.GroupLayout btnTagihanLayout = new javax.swing.GroupLayout(btnTagihan);
        btnTagihan.setLayout(btnTagihanLayout);
        btnTagihanLayout.setHorizontalGroup(
            btnTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTagihanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnTagihanLayout.setVerticalGroup(
            btnTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTagihanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gambarKartu.setBackground(new java.awt.Color(250, 243, 243));
        gambarKartu.setPreferredSize(new java.awt.Dimension(410, 257));

        lblNomorKartu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblNomorKartu.setForeground(new java.awt.Color(0, 0, 0));
        lblNomorKartu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomorKartu.setText("NOMOR");

        javax.swing.GroupLayout gambarKartuLayout = new javax.swing.GroupLayout(gambarKartu);
        gambarKartu.setLayout(gambarKartuLayout);
        gambarKartuLayout.setHorizontalGroup(
            gambarKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarKartuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomorKartu, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        gambarKartuLayout.setVerticalGroup(
            gambarKartuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarKartuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomorKartu, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnGantiPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAturLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gambarKartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJenisKartu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJenisKartu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarKartu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGantiPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAturLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAturLimitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAturLimitMouseClicked
        // TODO add your handling code here:
        uh.getContent().removeAll();
        UserProfileAturLimit ul = new UserProfileAturLimit(this);
        ul.passData(this);
        ul.setVisible(true);
        ul.setBounds(0,0, 500, 717);
        uh.getContent().add(ul);
        uh.getContent().revalidate();
        uh.getContent().repaint();
    }//GEN-LAST:event_btnAturLimitMouseClicked

    private void btnTagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTagihanMouseClicked
        // TODO add your handling code here:
        uh.getContent().removeAll();
        UserProfileTagihan upta = new UserProfileTagihan();
        upta.passData(this);
        upta.setVisible(true);
        upta.setBounds(0,0, 500, 717);
        uh.getContent().add(upta);
        uh.getContent().revalidate();
        uh.getContent().repaint();
    }//GEN-LAST:event_btnTagihanMouseClicked

    private void btnGantiPinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGantiPinMouseClicked
        // TODO add your handling code here:
        uh.getContent().removeAll();
        UserProfileGantiPin gp = new UserProfileGantiPin(this);
        gp.passData(this);
        gp.setVisible(true);
        gp.setBounds(0,0, 500, 717);
        uh.getContent().add(gp);
        uh.getContent().revalidate();
        uh.getContent().repaint();
    }//GEN-LAST:event_btnGantiPinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnAturLimit;
    private javax.swing.JPanel btnGantiPin;
    private javax.swing.JPanel btnTagihan;
    private javax.swing.JPanel gambarKartu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJenisKartu;
    private javax.swing.JLabel lblNomorKartu;
    // End of variables declaration//GEN-END:variables
}
