
package m.banking.Login;

import Calendar.CalendarFrame;
import Image.ImagePanel;
import RoundedField.RoundJPanel;
import RoundedField.RoundJPasswordField;
import RoundedField.RoundJTextField;
import ScrollBar.MyScrollBarUI;
import UI.AdminHomepage;
import UI.UserHomepage;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;
import m.banking.Gold;
import m.banking.Member;
import m.banking.Platinum;
import m.banking.Silver;


public class newAccount extends javax.swing.JFrame implements PropertyChangeListener {

    /**
     * Creates new form Login
     */
    int mousepX;
    int mousepY;
    Login l;
    ArrayList<Member> Account;
    ArrayList<Member> requestMember;
    CalendarFrame cf;
    public newAccount(Login l) {
        this.l = l;
        System.out.println(l.noRek);
        System.out.println(l.noRek.substring(0,4) + "-" + l.noRek.substring(4,8) + "-" + l.noRek.substring(8,12) + "-" + l.noRek.substring(12,16));
        initComponents();
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }
    
    public newAccount() {
        this.l = l;
        initComponents();
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }
    
    public void passLogin(Login l){
        this.l = l;
    }
    
    public void passAccount(ArrayList<Member> Account){
        this.Account = Account;
    }
    
    public void passRequestMember(ArrayList<Member> requestMember){
        this.requestMember = requestMember;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jenisKartu = new javax.swing.ButtonGroup();
        jPanel2 = new RoundJPanel(150);
        jPanel1 = new RoundJPanel(75);
        notch = new javax.swing.JLabel();
        jPanel3 = new RoundJPanel(50);
        createLbl = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Reset = new RoundJPanel(30);
        jLabel2 = new javax.swing.JLabel();
        Create = new RoundJPanel(30);
        jLabel3 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nomorHP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        silverBtn = new javax.swing.JRadioButton();
        goldBtn = new javax.swing.JRadioButton();
        platinumBtn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pin = new javax.swing.JPasswordField();
        confirmPin = new javax.swing.JPasswordField();
        tglLahir = new javax.swing.JFormattedTextField(DateFormat.getDateInstance(DateFormat.SHORT));
        btnPickDate = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);

        jPanel1 = new ImagePanel("src/m/banking/Asset/image.png");
        jPanel1.setOpaque(false);

        notch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/notch.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(250, 243, 243));
        jPanel3.setOpaque(false);

        createLbl.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        createLbl.setForeground(new java.awt.Color(0, 0, 0));
        createLbl.setText("Create New Account");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m/banking/Asset/Back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Reset.setBackground(new java.awt.Color(254, 174, 72));
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset.setOpaque(false);
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Reset");

        javax.swing.GroupLayout ResetLayout = new javax.swing.GroupLayout(Reset);
        Reset.setLayout(ResetLayout);
        ResetLayout.setHorizontalGroup(
            ResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        ResetLayout.setVerticalGroup(
            ResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        Create.setBackground(new java.awt.Color(84, 190, 229));
        Create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Create.setOpaque(false);
        Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Create");

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scroll.setBackground(new java.awt.Color(250, 243, 243));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.getVerticalScrollBar().setUI(new MyScrollBarUI());
        MouseAdapter ma = new MouseAdapter() {

            private Point origin;

            @Override
            public void mousePressed(MouseEvent e) {
                origin = new Point(e.getPoint());
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                if (origin != null) {
                    JViewport viewPort = (JViewport) SwingUtilities.getAncestorOfClass(JViewport.class, form);
                    if (viewPort != null) {
                        int deltaX = origin.x - e.getX();
                        int deltaY = origin.y - e.getY();

                        Rectangle view = viewPort.getViewRect();
                        view.x += deltaX;
                        view.y += deltaY;

                        form.scrollRectToVisible(view);
                    }
                }
            }

        };

        form.addMouseListener(ma);
        form.addMouseMotionListener(ma);

        form.setBackground(new java.awt.Color(250, 243, 243));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("First Name");

        firstName.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        firstName.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name");

        lastName.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lastName.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date of Birth");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gender");

        maleBtn.setBackground(new java.awt.Color(250, 243, 243));
        GenderGroup.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        maleBtn.setForeground(new java.awt.Color(0, 0, 0));
        maleBtn.setText("Male");
        maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnActionPerformed(evt);
            }
        });

        femaleBtn.setBackground(new java.awt.Color(250, 243, 243));
        GenderGroup.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        femaleBtn.setForeground(new java.awt.Color(0, 0, 0));
        femaleBtn.setText("Female");
        femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address");

        address.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        address.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Phone Number");

        nomorHP.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        nomorHP.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Member Card");

        silverBtn.setBackground(new java.awt.Color(250, 243, 243));
        jenisKartu.add(silverBtn);
        silverBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        silverBtn.setForeground(new java.awt.Color(0, 0, 0));
        silverBtn.setText("Silver");

        goldBtn.setBackground(new java.awt.Color(250, 243, 243));
        jenisKartu.add(goldBtn);
        goldBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        goldBtn.setForeground(new java.awt.Color(0, 0, 0));
        goldBtn.setText("Gold");

        platinumBtn.setBackground(new java.awt.Color(250, 243, 243));
        jenisKartu.add(platinumBtn);
        platinumBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        platinumBtn.setForeground(new java.awt.Color(0, 0, 0));
        platinumBtn.setText("Platinum");

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Card Number");

        saldo.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        saldo.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Saldo");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("XXXX-XXXX");
        jLabel12.setText(l.noRek.substring(0,4) + "-" + l.noRek.substring(4,8) + "-" + l.noRek.substring(8,12) + "-" + l.noRek.substring(12,16));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pin");

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Confirm Pin");

        pin.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        pin.setBorder(null);

        confirmPin.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        confirmPin.setBorder(null);

        tglLahir.setBorder(null);
        tglLahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        tglLahir.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        int year = l.d1.getD1().getYear()-1900;
        int month  = l.d1.getD1().getMonth()-1;
        int date = l.d1.getD1().getDate();
        tglLahir.setValue(new Date(year, month, date));
        System.out.println(tglLahir.getValue());
        System.out.println(l.d1.getD1().getYear() + " - " + l.d1.getD1().getMonth() + " - " + l.d1.getD1().getDate());

        btnPickDate.setBackground(new java.awt.Color(84, 190, 229));
        btnPickDate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel15.setText("Pick a Date");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnPickDateLayout = new javax.swing.GroupLayout(btnPickDate);
        btnPickDate.setLayout(btnPickDateLayout);
        btnPickDateLayout.setHorizontalGroup(
            btnPickDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPickDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPickDateLayout.setVerticalGroup(
            btnPickDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPickDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(tglLahir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPickDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addComponent(confirmPin, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(firstName)))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(maleBtn)
                        .addGap(36, 36, 36)
                        .addComponent(femaleBtn))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saldo)
                            .addComponent(address)
                            .addComponent(nomorHP)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(silverBtn)
                        .addGap(18, 18, 18)
                        .addComponent(goldBtn)
                        .addGap(18, 18, 18)
                        .addComponent(platinumBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglLahir)
                    .addComponent(btnPickDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleBtn)
                    .addComponent(femaleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(silverBtn)
                    .addComponent(goldBtn)
                    .addComponent(platinumBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        scroll.setViewportView(form);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(createLbl)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(createLbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(back)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(notch)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        
        this.setLocation(koordinatX-mousepX, koordinatY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        l.setVisible(true);
        
    }//GEN-LAST:event_backMouseClicked

    private void maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnActionPerformed

    private void femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleBtnActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        cf = new CalendarFrame();
        cf.addPropertyChangeListener(this);
        cf.setLocation(tglLahir.getLocationOnScreen().x, 
                (tglLahir.getLocationOnScreen().y + tglLahir.getHeight()));
        Date selectedDate = (Date) tglLahir.getValue();
        cf.resetSelection(selectedDate);
        cf.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        // TODO add your handling code here:
        this.firstName.setText("");
        this.lastName.setText("");
        this.tglLahir = new javax.swing.JFormattedTextField(DateFormat.getDateInstance(DateFormat.SHORT));
        this.tglLahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d MMMM yyyy"))));
        this.maleBtn.setSelected(false);
        this.femaleBtn.setSelected(false);
        this.address.setText("");
        this.nomorHP.setText("");
        this.silverBtn.setSelected(false);
        this.goldBtn.setSelected(false);
        this.platinumBtn.setSelected(false);
        this.saldo.setText("");
        this.pin.setText("");
        this.confirmPin.setText("");
        this.GenderGroup.clearSelection();
        this.jenisKartu.clearSelection();
        int year = l.d1.getD1().getYear()-1900;
        int month  = l.d1.getD1().getMonth()-1;
        int date = l.d1.getD1().getDate();
        this.tglLahir.setValue(new Date(year, month, date));
    }//GEN-LAST:event_ResetMouseClicked

    public boolean isNumeric(String str)
    {
        for (char c : str.toCharArray())
        {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    
    private void CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateMouseClicked
        // TODO add your handling code here:
        if (!firstName.getText().equals("")){
            if (!lastName.getText().equals("")){
                if ((maleBtn.isSelected() && !femaleBtn.isSelected()) || (!maleBtn.isSelected() && femaleBtn.isSelected())){
                    if (!address.getText().equals("")){
                        if (!nomorHP.equals("")){
                            if ((silverBtn.isSelected() && !goldBtn.isSelected() && !platinumBtn.isSelected()) ||
                                    (!silverBtn.isSelected() && goldBtn.isSelected() && !platinumBtn.isSelected()) ||
                                    (!silverBtn.isSelected() && !goldBtn.isSelected() && platinumBtn.isSelected())){
                                if (!saldo.getText().equals("")){
                                    String tempPin = new String(pin.getPassword());
                                    if (!tempPin.equals("")){
                                        if (pin.getPassword().length == 6){
                                            String tempConfirmPin = new String(confirmPin.getPassword());
                                            if (!tempConfirmPin.equals("")){
                                                if (confirmPin.getPassword().length == 6){
                                                    if (isNumeric(nomorHP.getText())){
                                                        if (isNumeric(saldo.getText())){
                                                            int jumlahSaldo = Integer.parseInt(saldo.getText());
                                                            if (jumlahSaldo >= 50000){
                                                                if (isNumeric(tempPin)){
                                                                    if (isNumeric(tempConfirmPin)){
                                                                        if (tempPin.equals(tempConfirmPin)){
                                                                            Date temp = (Date) tglLahir.getValue();
                                                                            //String temp = (String) tglLahir.getValue();
                                                                            System.out.println("- " + temp.getDate() + "/" + (temp.getMonth()+1) + "/" + ((temp.getYear()-100)+2000));
                                                                            String tempTgl = temp.getDate() + "/" + (temp.getMonth()+1) + "/" + ((temp.getYear()-100)+2000);
                                                                            //System.out.println(temp);
                                                                            System.out.println((l.d1.getD1().getYear() - ((temp.getYear()-100)+2000)));
                                                                            if ((l.d1.getD1().getYear() - ((temp.getYear()-100)+2000)) >= 18){
                                                                                System.out.println((l.d1.getD1().getYear() - ((temp.getYear()-100)+2000)));
                                                                                System.out.println(l.d1.getD1().getYear()-18);
                                                                                System.out.println(((temp.getYear()-100)+2000));
                                                                                if (silverBtn.isSelected()){
                                                                                    if (maleBtn.isSelected()){
                                                                                        l.requestMember.add(new Silver((firstName.getText() + " " + lastName.getText()).toUpperCase(), Double.parseDouble(saldo.getText()), l.noRek, nomorHP.getText(), address.getText(), tempPin, tempTgl, "Male"));
                                                                                    }
                                                                                    else if (femaleBtn.isSelected()){
                                                                                        l.requestMember.add(new Silver((firstName.getText() + " " + lastName.getText()).toUpperCase(), Double.parseDouble(saldo.getText()), l.noRek, nomorHP.getText(), address.getText(), tempPin, tempTgl, "Female"));
                                                                                    }
                                                                                }
                                                                                else if (goldBtn.isSelected()){
                                                                                    if (maleBtn.isSelected()){
                                                                                        l.requestMember.add(new Gold((firstName.getText() + " " + lastName.getText()).toUpperCase(), Double.parseDouble(saldo.getText()), l.noRek, nomorHP.getText(), address.getText(), tempPin, tempTgl, "Male"));
                                                                                    }
                                                                                    else if (femaleBtn.isSelected()){
                                                                                        l.requestMember.add(new Gold((firstName.getText() + " " + lastName.getText()).toUpperCase(), Double.parseDouble(saldo.getText()), l.noRek, nomorHP.getText(), address.getText(), tempPin, tempTgl, "Female"));
                                                                                    }
                                                                                }
                                                                                else if (platinumBtn.isSelected()){
                                                                                    if (maleBtn.isSelected()){
                                                                                        l.requestMember.add(new Platinum((firstName.getText() + " " + lastName.getText()).toUpperCase(), Double.parseDouble(saldo.getText()), l.noRek, nomorHP.getText(), address.getText(), tempPin, tempTgl, "Male"));
                                                                                    }
                                                                                    else if (femaleBtn.isSelected()){
                                                                                        l.requestMember.add(new Platinum((firstName.getText() + " " + lastName.getText()).toUpperCase(), Double.parseDouble(saldo.getText()), l.noRek, nomorHP.getText(), address.getText(), tempPin, tempTgl, "Female"));
                                                                                    }
                                                                                }
                                                                                String filename = "requestMember.ser";
                                                                                try {
                                                                                    FileOutputStream file = new FileOutputStream(filename);
                                                                                    ObjectOutputStream out = new ObjectOutputStream(file);

                                                                                    out.writeObject(l.requestMember);

                                                                                    out.close();
                                                                                    file.close();

                                                                                    System.out.println("Object has been serialized");

                                                                                }
                                                                                catch(IOException ex) {
                                                                                    System.out.println("IOException is caught");
                                                                                }
                                                                                JOptionPane.showMessageDialog(this, "Berhasil membuat member.. tunggu konfirmasi dari admin");
                                                                                this.setVisible(false);
                                                                                l.setVisible(true);
                                                                            }
                                                                            else {
                                                                                JOptionPane.showMessageDialog(this, "Umur minimal 18 tahun");
                                                                            }
                                                                        }
                                                                        else {
                                                                            JOptionPane.showMessageDialog(this, "Confirm Pin tidak sesuai");
                                                                        }
                                                                    }
                                                                    else {
                                                                        JOptionPane.showMessageDialog(this, "Confirm Pin Harus digit");
                                                                    }
                                                                }
                                                                else {
                                                                    JOptionPane.showMessageDialog(this, "Pin Harus digit");
                                                                }
                                                            }
                                                            else {
                                                                JOptionPane.showMessageDialog(this, "Saldo minimum 50000");
                                                            }
                                                        }
                                                        else {
                                                            JOptionPane.showMessageDialog(this, "Saldo Harus digit");
                                                        }
                                                    }
                                                    else {
                                                        JOptionPane.showMessageDialog(this, "Nomor HP Harus digit");
                                                    }
                                                }
                                                else {
                                                    JOptionPane.showMessageDialog(this, "Confirm Pin harus 6 digit angka");
                                                }
                                            }
                                            else {
                                                JOptionPane.showMessageDialog(this, "Confirm Pin harus diisi");
                                            }
                                        }
                                        else {
                                            JOptionPane.showMessageDialog(this, "pin harus 6 digit angka");
                                        }
                                    }
                                    else {
                                        JOptionPane.showMessageDialog(this, "Pin harus diisi");
                                    }
                                }
                                else {
                                    JOptionPane.showMessageDialog(this, "Saldo harus diisi");
                                }
                            }
                            else {
                                JOptionPane.showMessageDialog(this, "Jenis Kartu harus diisi");
                            }
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "Nomor HP harus diisi");
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Address harus diisi");
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this, "Gender harus diisi");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Last Name harus diisi");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "First Name harus diisi");
        }
    }//GEN-LAST:event_CreateMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Create;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JPanel Reset;
    private javax.swing.JTextField address;
    private javax.swing.JLabel back;
    private javax.swing.JPanel btnPickDate;
    private javax.swing.JPasswordField confirmPin;
    private javax.swing.JLabel createLbl;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JTextField firstName;
    private javax.swing.JPanel form;
    private javax.swing.JRadioButton goldBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup jenisKartu;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JTextField nomorHP;
    private javax.swing.JLabel notch;
    private javax.swing.JPasswordField pin;
    private javax.swing.JRadioButton platinumBtn;
    private javax.swing.JTextField saldo;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JRadioButton silverBtn;
    private javax.swing.JFormattedTextField tglLahir;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent event) {
        if (event.getPropertyName().equals("selectedDate")){
            java.util.Calendar cal = (java.util.Calendar) event.getNewValue();
            Date selDate = cal.getTime();
            tglLahir.setValue(selDate);
        }
    }
}
